title      : Yangtze
lang       : zh-CN
description: <address>webmaster &lt;zy@yangtze.in&gt;</address> [![](https://www.eff.org/files/brstrip.gif)](https://www.eff.org/pages/blue-ribbon-campaign)
copyright  : © 2021-2023 Yangtze. All Rights Reserved.

nav:
 - name: 首页
   link: /         # link 是 pages 里面的文件名中的permalink，此处格式为 /forexample/
 - name: 博客
   link: /blog/
 - name: 关于
   link: /about/
