title      : Admirelight | 仰光
lang       : zh-cn
description: 科技改变生活...
copyright  : © 2021-2022 Admirelight. All Rights Reserved.

nav:
 - name: 首页
   link: /
 - name: 博客
   link: /blog/         # link 是 pages 里面的文件名中的permalink，此处格式为 /forexample/
