title      : YangOpenSource
lang       : zh-cn
description: 科技改变生活...
copyright  : © 2021-2022 YangOpenSource. All Rights Reserved.

nav:
 - name: 首页
   link: /
 - name: 待定
   link: /#/            # link 是 pages 里面的文件名中的permalink
