title      : Yangtze
lang       : zh-CN
description: <address>webmaster &lt;zy@yangtze.in&gt;</address>
copyright  : © 2021-2023 Yangtze. Powered by <a href="http://netlify.com" target="_blank"><img src="https://b2.yangtze.in/pic/img/Netlify_logo.svg"></a>

nav:
 - name: 首页
   link: /        # link 是 pages 里面的文件名中的permalink，此处格式为 /forexample/
 - name: 博客
   link: /blog/
 - name: 关于
   link: /about/
