title      : Yangtze
lang       : zh-cn
description: <address>webmaster &lt;tarns@qq.com&gt;</address>
copyright  : © 2021-2022 Yangtze. All Rights Reserved.

nav:
 - name: 首页
   link: /         # link 是 pages 里面的文件名中的permalink，此处格式为 /forexample/
 - name: 博客
   link: /blog/
 - name: 关于
   link: /about/
