title      : Nanking
lang       : zh-cn
description: 每件事都要会亿点点……
copyright  : © 2021-2022 Nanking. All Rights Reserved.

nav:
 - name: 首页
   link: /         # link 是 pages 里面的文件名中的permalink，此处格式为 /forexample/
 - name: 目录
   link: /blog/
 - name: 关于
   link: /about/
